name: Ubuntu 18.04

# Dependencies of this package
env:
  MACOS_BREW: ${{ 'cairo glib glib-networking gobject-introspection pkg-config jq' }}
  UBUNTU_APT: ${{ 'libcairo2-dev libcairo-gobject2 libglib2.0-dev glib-networking gobject-introspection libgirepository1.0-dev libxml2-dev jq' }}

on:
  push:
    branches:
      - development
      - main
  pull_request:
    branches:
      - development
      - main

jobs:
  # Ubuntu 18.04 tasks
  build-ubuntu-18_04-swift-latest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: YOCKOW/Action-setup-swift@v1
        with:
          swift-version: '5.6'

      - name: Print Swift version to confirm
        run: swift --version
      - name: Fetch dependencies for general repository
        run: sudo apt-get install $UBUNTU_APT

      - name: Checkout SwiftCairo
        uses: actions/checkout@v2
        with:
          path: SwiftCairo

      - name: Build SwiftCairo
        run: |
          cd SwiftCairo
          swift build
          cd ..

      - name: Test SwiftCairo
        run: |
          cd SwiftCairo
          swift test
          cd ..

      - name: Remove unneeded files and archive artifacts
        run: |
          cd SwiftCairo
          swift package clean
          rm -rf .build/repositories
          cd ..

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-18.04-5.3
          path: |
            SwiftCairo/Sources/
          retention-days: 1
